# Generated by Django 3.2.7 on 2022-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='目標')),
                ('content', models.TextField(blank=True, null=True, verbose_name='振り返り')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Goal',
            },
        ),
    ]
